#!/usr/bin/env bash
# Everything CI runs before a deploy. Run it locally before pushing.
set -euo pipefail
cd "$(dirname "$0")/.."

fail=0
say() { echo "$*"; }

# 1) PHP syntax, on every file that will be uploaded
while IFS= read -r -d '' f; do
  php -l "$f" >/dev/null || { say "PHP syntax error: $f"; fail=1; }
done < <(find wp-content -name '*.php' -print0)

# 2) Every plugin has <slug>/<slug>.php with a Version header (zip.sh and the updater rely on it)
for dir in wp-content/plugins/*/; do
  slug=$(basename "$dir")
  grep -qP '^\s*\*\s*Version:\s*[0-9.]+' "$dir$slug.php" 2>/dev/null || { say "$slug: $slug.php with a Version header is required"; fail=1; }
done

# 2b) Plugin header Version must equal STLH_VER (it is the CSS/JS cache-buster)
main=wp-content/plugins/stland-home/stland-home.php
hv=$(grep -oP '^\s*\*\s*Version:\s*\K[0-9.]+' "$main")
cv=$(grep -oP "define\(\s*'STLH_VER',\s*'\K[0-9.]+" "$main")
if [ "$hv" != "$cv" ]; then
  say "stland-home: header Version ($hv) != STLH_VER ($cv)"; fail=1
fi

# 3) Contract with the accounting app: card badge meta keys
for key in $(php -r 'echo implode(" ", json_decode(file_get_contents("contract/card-meta.json"), true)["keys"]);'); do
  if ! grep -qP "'card_badges'.*(\"|\\\\n)$key\|" wp-content/plugins/stland-home/includes/helpers.php; then
    say "contract: card_badges default is missing meta key '$key' (see contract/card-meta.json)"; fail=1
  fi
done

# 3b) Contract version and spec keys
want=$(php -r 'echo json_decode(file_get_contents("contract/card-meta.json"), true)["version"];')
have=$(grep -oP "define\(\s*'STLH_CONTRACT',\s*\K[0-9]+" "$main")
if [ "$want" != "$have" ]; then
  say "contract: STLH_CONTRACT ($have) != contract/card-meta.json version ($want)"; fail=1
fi
for key in $(php -r 'echo implode(" ", json_decode(file_get_contents("contract/card-meta.json"), true)["spec"]);'); do
  if ! grep -q "'$key'" wp-content/plugins/stland-home/includes/render.php; then
    say "contract: spec key '$key' is not read in render.php (stlh_spec_line)"; fail=1
  fi
done

for key in $(php -r 'echo implode(" ", json_decode(file_get_contents("contract/card-meta.json"), true)["seo"] ?? []);'); do
  if ! grep -q "'$key'" wp-content/plugins/stland-home/includes/seo-bridge.php; then
    say "contract: seo key '$key' is not bridged in seo-bridge.php"; fail=1
  fi
done

for key in $(php -r 'echo implode(" ", json_decode(file_get_contents("contract/card-meta.json"), true)["product"] ?? []);'); do
  if ! grep -q "'$key'" wp-content/plugins/stland-home/includes/product-page.php; then
    say "contract: product key '$key' is not read in product-page.php"; fail=1
  fi
done

# 4) Never ship generated or secret files
if git ls-files --error-unmatch wp-content/mu-plugins/stland-site/build.php >/dev/null 2>&1; then
  say "build.php is generated by the deploy workflow; do not commit it"; fail=1
fi

[ "$fail" = 0 ] && say "OK (stland-home $hv)"
exit "$fail"
