#!/usr/bin/env bash
# Everything CI runs before a deploy. Run it locally before pushing.
set -euo pipefail
cd "$(dirname "$0")/.."

fail=0
say() { echo "$*"; }

# 1) PHP syntax, on every file that will be uploaded
while IFS= read -r -d '' f; do
  php -l "$f" >/dev/null || { say "PHP syntax error: $f"; fail=1; }
done < <(find wp-content -name '*.php' -print0)

# 2) Plugin header Version must equal STLH_VER (it is the CSS/JS cache-buster)
main=wp-content/plugins/stland-home/stland-home.php
hv=$(grep -oP '^\s*\*\s*Version:\s*\K[0-9.]+' "$main")
cv=$(grep -oP "define\(\s*'STLH_VER',\s*'\K[0-9.]+" "$main")
if [ "$hv" != "$cv" ]; then
  say "stland-home: header Version ($hv) != STLH_VER ($cv)"; fail=1
fi

# 3) Contract with the accounting app: card badge meta keys
for key in $(php -r 'echo implode(" ", json_decode(file_get_contents("contract/card-meta.json"), true)["keys"]);'); do
  if ! grep -qP "'card_badges'.*(\"|\\\\n)$key\|" wp-content/plugins/stland-home/includes/helpers.php; then
    say "contract: card_badges default is missing meta key '$key' (see contract/card-meta.json)"; fail=1
  fi
done

# 4) Never ship generated or secret files
if git ls-files --error-unmatch wp-content/mu-plugins/stland-site/build.php >/dev/null 2>&1; then
  say "build.php is generated by the deploy workflow; do not commit it"; fail=1
fi

[ "$fail" = 0 ] && say "OK (stland-home $hv)"
exit "$fail"
